### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by WangDeyu** [xuyuan/x-force#5]
我看到您在讲解的文档中的总结部分贴出了一个实验结果的表格，其中job3975和job4010，job4298和job4334中结构和算法都一致但是性能有了明显的提升，请问是为什么？用到了方法么？

**Comment by xuyuan** [comment]
* job4010是一个笔误，其实是用了unet2
* job4298训练的输入图片大小是256，job4334是在此基础上用384图像进一步训练的

**Comment by WangDeyu** [comment]
@xuyuan 好的，谢谢！
